version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
  # database server
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"

volumes:
  db:

