FROM node:latest
WORKDIR /code
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh
COPY /package.json /package.json
RUN cd / && npm install -g
RUN rm -rf /node_modules/@tensorflow/tfjs-converter/.git

RUN cd / && rm -rf /node_modules/node-sass && npm install node-sass # work around https://github.com/sass/node-sass/issues/1579
ADD ./ /code

RUN mkdir -p /tmp/psql_data/

COPY dbschema.sql /tmp/psql_data/
COPY init_docker_postgres.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/


CMD npm run dev